// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJidT4koIZSEQWE4v78IKKWtTyygnieGg',
    appId: '1:705468697207:web:117e629735217335ee1472',
    messagingSenderId: '705468697207',
    projectId: 'immunowarriors-eda89',
    authDomain: 'immunowarriors-eda89.firebaseapp.com',
    storageBucket: 'immunowarriors-eda89.firebasestorage.app',
    measurementId: 'G-YK3L4DZ768',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIZtIoOgYvJPIbJ_GhW8KcK8qHSIZSnmo',
    appId: '1:705468697207:android:f6192fab67d46ecbee1472',
    messagingSenderId: '705468697207',
    projectId: 'immunowarriors-eda89',
    storageBucket: 'immunowarriors-eda89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLsavx8q7CBVc042WEDbhfunJUzw-QRRg',
    appId: '1:705468697207:ios:470492322bf526b8ee1472',
    messagingSenderId: '705468697207',
    projectId: 'immunowarriors-eda89',
    storageBucket: 'immunowarriors-eda89.firebasestorage.app',
    iosBundleId: 'com.example.immunowarriors',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLsavx8q7CBVc042WEDbhfunJUzw-QRRg',
    appId: '1:705468697207:ios:470492322bf526b8ee1472',
    messagingSenderId: '705468697207',
    projectId: 'immunowarriors-eda89',
    storageBucket: 'immunowarriors-eda89.firebasestorage.app',
    iosBundleId: 'com.example.immunowarriors',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJidT4koIZSEQWE4v78IKKWtTyygnieGg',
    appId: '1:705468697207:web:6029724a20bf65c8ee1472',
    messagingSenderId: '705468697207',
    projectId: 'immunowarriors-eda89',
    authDomain: 'immunowarriors-eda89.firebaseapp.com',
    storageBucket: 'immunowarriors-eda89.firebasestorage.app',
    measurementId: 'G-Q0LV7GNRXW',
  );
}
